name: checkstyle-on-pull-request
on: [ pull_request ]
jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.1.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
